### ISSUE TITLE
Add support for ALGORITHM and LOCK clauses in ALTER TABLE statements

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#114]
https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl.html
https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl.html

```
==> ALTER TABLE `test`
  ADD COLUMN `column1` DATETIME NULL,
  ALGORITHM=INPLACE,
  LOCK=NONE
Position 6:11 Tokens: ALGORITHM=INPLACE,
  LOCK=NONE
Error: Sqlgg.Sql_parser.MenhirBasics.Error
```

**Comment by jongleb** [comment]
https://github.com/ygrek/sqlgg/pull/137
https://github.com/ygrek/sqlgg/commit/990316d7375d6381e86a81de56c45b87b0a57bb5
