### ISSUE TITLE
Get rid of deriving/camlp4

### ISSUE THREAD

**Issue by rgrinberg** [ygrek/sqlgg#35]
Seems like deriving is only used for pretty printing (`show` instance) and [ppx_deriving](https://github.com/whitequark/ppx_deriving) can cover the same use case without camlp4.

Would it be possible to switch to it?

**Comment by ygrek** [comment]
Guess so, but I never thought of it as a problem, why? Do you have a specific usecase?
Also keep in mind that ppx will limit it to be installable only with most recent OCaml version.

**Comment by rgrinberg** [comment]
I have some weak VPS's where compiling camlp4 runs out of memory so it's a bit of a pain. But not having sqlgg on recent versions of OCaml is a real downside so I agree with you.
