### ISSUE TITLE
add support for `datetime` function (sqlite)

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#53]
See https://www.sqlite.org/lang_datefunc.html for reference.

As of now, only the following form is needed:
```
SELECT datetime(1092941466, 'unixepoch');
```

**Comment by ygrek** [comment]
Cannot express multi-type function signatures for now (in this case datetime first arguments can be float or string), but will explout the fact that datetime accepts timestamp in string representation too. In general, currently datetime type story is not very defined..
