### ISSUE TITLE
DECIMAL(N, M) is mapped to integer

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#75]
I expect column of type `decimal(N, M)` to be floats on the OCaml side, at least if M<>0, but sqlgg assumes the type to be integer instead.
```
$ cat /tmp/test.sql                                                                                                        
create table foo ( bar decimal(10, 2) );
insert into foo ( bar ) values;
select bar from foo;
```
```
$ sqlgg -params named -gen caml /tmp/test.sql
(* DO NOT EDIT MANUALLY *)
(*  *)
(* generated by sqlgg 0.4.5 on 2019-09-19T06:58Z *)

module Sqlgg (T : Sqlgg_traits.M) = struct

  module IO = Sqlgg_io.Blocking

  let create_foo db  =
    T.execute db ("create table foo ( bar decimal(10, 2) )") T.no_params 

  let insert_foo_1 db ~bar =
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p bar;
      T.finish_params p
    in
    T.execute db ("insert into foo ( bar ) values (@bar)") set_params 

  let select_2 db  callback =
    let invoke_callback stmt =
      callback
        ~bar:(T.get_column_Int stmt 0)
    in
    T.select db ("select bar from foo") T.no_params invoke_callback

  module Fold = struct
    let select_2 db  callback acc =
      let invoke_callback stmt =
        callback
          ~bar:(T.get_column_Int stmt 0)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("select bar from foo") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

  end (* module Fold *)
  
  module List = struct
    let select_2 db  callback =
      let invoke_callback stmt =
        callback
          ~bar:(T.get_column_Int stmt 0)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("select bar from foo") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

  end (* module List *)
end (* module Sqlgg *)
```

**Comment by zindel** [comment]
Bump. Hit this one today too

**Comment by yawaramin** [comment]
It's actually probably safer to map SQL DECIMAL(M,N) fields to OCaml int than float. Floats suffer from representation issues due to being encoded in binary, while SQL DECIMAL is, of course, encoded in decimal radix. So if you read 0.1 into a float, that's already inexact vs reading into an int 1 with scale -1.

You might also want to consider using a decimal library like Jane Street's Bigdecimal or my Decimal, which offer decimal-based encoding and operations.

**Comment by ygrek** [comment]
as we can see [in the commit above](https://github.com/ygrek/sqlgg/commit/6f72015a3483e4f43dd9fa483677df0003e1a7de#diff-080579952fb3ca76eab28b5486112bfe26d6ba34f8f0edcd115f0a37aee1a168R9) sql decimal type is mapped to a separate type and traits can map that to whatever type deemed adequate in the host language ([float being a default in the supplied traits](https://github.com/ygrek/sqlgg/commit/6f72015a3483e4f43dd9fa483677df0003e1a7de#diff-ce149a8aa0b3441a421604b03f64fcea37e372048b82b102f6d400fbef01d170R105))
