### ISSUE TITLE
insert null values

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#78]
```
create table test (
  id integer primary key auto_increment,
  column1 int not null,
  column2 int null,
  column3 int null default 0
)
-- insert
insert into test ( id, column1, column2, column3 )
  values ( @id, @column1, @column2, @column3 );
```
```
Sql.insert dbd ~id ~column1 ~column2 ~column3
```
`column1` must accept int, but `column2`, `column3`, and `id` (because of auto_increment) must accept `int option`.

**Comment by cyberhuman** [comment]
Another point to make is that inserts that don't mention `NOT NULL` columns without a `DEFAULT` value must be rejected.

**Comment by ygrek** [comment]
ftr this is implemented, except for sanity checking wrt annotations on column definitions (NULL against DEFAULT)
