### ISSUE TITLE
add support for DATE(), TIME()

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#84]
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_time
I see some mentions of these functions in `sql.ml` but it doesn't work because apparently DATE and TIME are recognized as column types.

**Comment by ygrek** [comment]
meh, in sqlite workaround with quoting works, but not in mysql :
```
MariaDB [(none)]> select `date`(current_timestamp);
ERROR 1305 (42000): FUNCTION date does not exist
```
