### ISSUE TITLE
sql syntax: support 'field in @list_param`

### ISSUE THREAD

**Issue by zindel** [ygrek/sqlgg#85]
It'd be great if this syntax could be supported:
```sql
SELECT x, y, z FROM t WHERE z in @list
```

The current workaround which limits the number of items in `@list` is:
```sql
SELECT x, y, z
FROM t
WHERE
  @z1 { Some { z = @z1 } | None { FALSE }} OR
  @z2 { Some { z = @z2 } | None { FALSE }} OR
...
```
which is kinda ugly :(

Thanks!

**Comment by ygrek** [comment]
implemented in #104 and being improved in #109
