### ISSUE TITLE
insert default value explicitly

### ISSUE THREAD

**Issue by cyberhuman** [ygrek/sqlgg#88]
```
sqlgg - <<EOF
create table test ( foo integer not null default 12345 );
insert into test ( foo ) values ( default );
EOF
==> insert into test ( foo ) values ( default )
Position 1:41 Tokens: default )
Error: Sqlgg.Sql_parser.MenhirBasics.Error
Errors encountered, no code generated
```

according to https://dev.mysql.com/doc/refman/8.0/en/insert.html:
> Use the keyword DEFAULT to set a column explicitly to its default value. This makes it easier to write INSERT statements that assign values to all but a few columns, because it enables you to avoid writing an incomplete VALUES list that does not include a value for each column in the table. Otherwise, you must provide the list of column names corresponding to each value in the VALUES list.

**Comment by cyberhuman** [comment]
```sqlgg -gen caml - <<EOF
create table test ( foo integer not null default 12345 );
insert into test ( foo ) values ( @choice { Def { default } } );
EOF
==> insert into test ( foo ) values ( @choice { Def { default } } )
Position 1:59 Tokens: } } )
Error: Sqlgg.Sql_parser.MenhirBasics.Error
Errors encountered, no code generated```

**Comment by ygrek** [comment]
ftr suggested workaround is to use `DEFAULT(foo)`
